### ISSUE TITLE
Explore podsecuritycontext for cvmfs id mapping

### ISSUE THREAD

**Issue by tclose** [Australian-Imaging-Service/charts#163]
```
podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 2000
```
```
fsGroup: 2000
Is used for CSI driver ID mapping
```
