### ISSUE TITLE
Using postgresqlEnabled: False still creates a postgresql pod

### ISSUE THREAD

**Issue by exxa-tech** [Australian-Imaging-Service/charts#58]
My values file:
```
global:
  postgresql:
    postgresqlDatabase: "XXXXX"
    postgresqlUsername: "XXXXX"
    postgresqlPassword: "XXXXXXX"
postgresqlEnabled: false
```
It creates both.

```
pod/xnat-xnat-web-0     1/1     Running   0          2d18h

service/xnat-postgresql            ExternalName   <none>           xnat-eks-rds.cluster-cv6zrphdzqjm.ap-southeast-2.rds.amazonaws.com   <none>           2d18h
```

Perhaps the Chart.yaml is wrongly configured somehow?

```
  condition: postgresql.enabled,postgresqlEnabled
```
